### ISSUE TITLE
Suggestion: Ghost ban mode/ban ideas

### ISSUE THREAD

**Issue by TheVingard** [DerekSM/anus#10]
1. You could possibly add a FAdmin like ban screen that pops up while being banned.
2. When banned you will join the server but a fancy UI will popup with the ban reason ect, it could contain buttons and links to places to appeal ect. This UI would make a sound when it pops-up and the player will stay connected for 30-90 seconds until they are auto-kicked. This system allows a neater, nicer interface that can show the whole ban reason and display additional things like a website link ect.
3. Add cooldown. A cooldown is similar to a ban (it would contain a time and reason) but would put the player in a spectate like mode. They would not be able to use chat or any form of communitcation or even spawn. They would simply be in a TTT like spectate mode. The reason would be at the top of the screen and if the server is full they would be kicked.
4. Weapon ban, stops players from using weapons. Good for RP servers. Reason and time left displayed.
5. Server annoucement. Simple. Like the FAdmin "listen up" GUI. But, with the sexy UI of anus.
6. Team blacklist, simple
7. Disguise system, will disguise admins when they run the command as a user on the scoreboard.
8. Finally, I a Admin Sided Ui for the report system could be cool: http://images.weserv.nl/?url=//s3.scriptfodder.com/script_media/9fa40d588667c79e1bcc001807894dda.png&w=193&h=100&t=square&output=jpg like this. In top left of admins screen

Thanks, I know these are allot of suggestions and some of them are probably too time consuming but thanks for reading.

**Comment by DerekSM** [comment]
I'll definitely be implementing some of these, but as for suggestion # 7, I have already had planned for a while now is that notifications still persist, but the admin name is masked with a randomly generated name such as "Admin 4zk-1932 has __________ playername"

**Comment by DerekSM** [comment]
1. Probably not
2. Ditto
3. Ditto
4. Ditto
5. Done
6. Maybe later
7. Done
8. I don't know yet.
