### ISSUE TITLE
Suggestion: Some input for the scoreboard.

### ISSUE THREAD

**Issue by TheVingard** [DerekSM/anus#11]
Here are a few suggestion to what I think makes a nice admin scoreboard.
1. Immunity effects placement, highest ranks are at the top.
2. Admins stand out, possibly with bold names, or pulsing colours. http://images.akamai.steamusercontent.com/ugc/395550873908319831/403D602BEB2D1F9E6F705F27887D785C11183E79/
3. Dropdown menu. Like PERP's if you have ever seen it (A bit like [this](http://img2.wikia.nocookie.net/__cb20091026184816/gmod/images/1/1f/Sandbox_scoreboard_opened.jpg) but with admin options kick ect. Maybe have icons with numbers like past bans ect or warnings?)
4. Things for admins (GeoIP country in name like Vingard [United Kingdom] or [Admin] Vingard [United Kindgom] this would only be for admins) also admins see Team?
5. Possibly a button at the top to make a report. Seeing that there are so many different report commands. (@, /report, !report, ect.)

Good luck with the development of this admin mod! Your doing a great job! :)

**Comment by DerekSM** [comment]
Thanks for the input! The goal of this admin mod is to be effective and to also be hidden from normal players. This means that normal players will NOT be able to see who's admin on the scoreboard, only other admins will, just making that clear haha.

I'll definitely come back to this page for ideas on the scoreboard, thanks again

**Comment by TheVingard** [comment]
Ah, nice. Could you make the ability to view admins on the scoreboard permission based. So groups like "trusted" could see online staff? Thanks :)

**Comment by DerekSM** [comment]
Admins aren't supposed to stand out. They're supposed to be in the shadows.
Base sandbox scoreboard now has commonly used admin functions implemented.
Added ability for groups to see admins.
