### ISSUE TITLE
Suggestion: A way for donations

### ISSUE THREAD

**Issue by LewisLector** [DerekSM/anus#13]
Just a way to set Perm donations via PData or something like that.

So that people don't need to stack on vipmod and shit like that.

**Comment by DerekSM** [comment]
set perm donations? What do you mean

**Comment by LewisLector** [comment]
So my moderator donates. and I don't want to have to make a whole new group to add him to vip.

Rather make a IsVIP()

**Comment by DerekSM** [comment]
Like a per-user permission editor? Was planned and still is but likely won't be implemented for a while.
