### ISSUE TITLE
Watching players and ban errors

### ISSUE THREAD

**Issue by TheVingard** [DerekSM/anus#5]
In the watch menu nothing happens and the ban menu gives the error:

[ERROR] addons/anus-master/lua/anus/plugins/cl_ban.lua:144: bad argument #1 to '(for generator)' (table expected, got nil)
  1. (for generator) - [C]:-1
   2. CreatePage - addons/anus-master/lua/anus/plugins/cl_ban.lua:144
    3. DoClick - addons/anus-master/lua/anus/plugins/cl_ban.lua:42
     4. unknown - lua/vgui/dlabel.lua:218

**Comment by codethrax** [comment]
This error can be replicated by doing the following:

https://vid.me/TqtJ

**Comment by DerekSM** [comment]
Fixed
