### ISSUE TITLE
Is ANUS causing a connection issue?

### ISSUE THREAD

**Issue by TheVingard** [DerekSM/anus#8]
I think anus is causing this:
Dropped Darkskelly #5haun4Emperor from server (Failed to auth. Try to reconnect.)
When it checks users.

This error does not occur with ULX or when ANUS is disabled.

**Comment by DerekSM** [comment]
Yeah that's a check in autorun/server/sv_load.lua
If players aren't authed they are bugged out in several things so they are kicked automatically.
I'll increase time limit from 13.5 seconds to 30

The check is ran in PlayerInitialSpawn, so about the time the player is sending client info.
Didn't think it would take players 13 seconds to send client info, but it'll be increased nonetheless.

**Comment by DerekSM** [comment]
No disagrees? alright closing
